ReactNativeNews/React-Native-Apps

README.md

Short-term memory training game. Free, no ads, open source.
https://github.com/sobstel/sequent

Added Sequent game

---

README.md

Dear, 
I would like to add my project to this repo. I'm available for any questions.
Kind Regards.
Pablo Darde

DARDE, React Native Sidemenu

---

README.md

Our Github:
http://github.com/status-im/status-react
Build Instructions:
https://wiki.status.im/contributing/development/building-status/
Android Binaries:
https://play.google.com/apps/testing/im.status.ethereum
Video of it in action:
https://www.youtube.com/watch?v=oDCSEmS9c3o

add Status to README.md

---

README.md

I've added an Urban Dictionary Client app to the list.

Added Urban Dictionary

---

README.md

F1 Stats app

---

README.md

I added a React Native Netflix App open source using the latest component FlatList.

Netflix App added

---

README.md

Its a simple app where you can save your location and get direction to it at a later time
Google play link: https://play.google.com/store/apps/details?id=com.locationsaver

Added Location Saver

---

README.md

A lot of new RN developers have enjoyed reading my code, so i figured that i'd add it as a resource here

Adds PÜL to app list

---

README.md

It's like an Instagram or Facebook designed specially for pets

Added Thousanday - Homepage for pets

---

README.md

The case is a cool comic books app used redux, supporting iOS and Android

Add cool comic book app

---

README.md

Unofficial DuckDuckGo app in React-Native. https://github.com/kiok46/duckduckgo

Added - DuckDuckGo App (Unofficial)

---

README.md

https://github.com/RCiesielczuk/HackerBuzz-ReactNative
Thanks!

Add Hacker Buzz

---

README.md

Code is not open source yet, I have to clean my repo, but I will do it asap :) (that's why I put a link).

Add "Hide The Notch" app

---

README.md

I hope this will help dev community. thank you.

Added Facebook Official F8 Open Source App

---

README.md

- Added a application build with react native and also open soure called **Arxiv papers**.
- Removed some unnecessary white space.

Added arxiv papers app

---

README.md

Add eLadder app

---

README.md

Thanks for this awesome showcase !

Add Moonwalk

---

README.md

Stylish puzzle adventure. Nearly 20k downloads at the App Store, ~4.5 from 166 reviewers. Now open-sourced. 
https://www.hydropuzzle.com/

Add Hydropuzzle game

---

README.md

Adding Lyrics King open source app

Adding Lyrics King

---

README.md

-Modern Twin Calculator
-BMI Calculator

Two new Apps added

---

README.md

Give credit where credit is due! <3

Added Gant byline in footer

---

README.md

http://shootismoke.github.io/
Shamelessly putting my app on 1st pos. I'm happy to put it lower in the list if the authors ask so.

feat: add "Sh**t! I Smoke"

---

README.md

Adding Helo Protocol to list of React Native apps

---

README.md

feat: add WordsReminder

---

README.md

Exponent -> Expo

---

README.md

I just release Meet Native : an app to locate language partner
Integrations: Typescript, Graphql, Redux-Saga, Firebase...

add Meet Native

---

README.md

My first ever pull request (hope I don't stuff it up).

Added Tip Advisor and Tone Tracker apps

---

README.md

Would really appreciate if you can add this app of mine to the repository.
LMK if there's anything missing from this PR.

Add SmallSteps

---

README.md

Add [NMF.earth](https://nmf.earth/) open source app

Add NMF.earth app

---

README.md

https://infinite.red/react-native is 404 not found. Maybe move to https://infinite.red/technologies/react-native .

Fix link to Infinite Red is 404

---

README.md

There were some stale sections; I updated them.

Refresh some sections of the README
